from __future__ import annotations

from typing import Literal, cast

PixelColorTheme = Literal[
    "simdt_blue",
    "warm_amber",
    "race_gyr",
    "arcade_neon",
    "pit_lane_white",
    "night_vision",
    "gulf_classic",
    "ice_rally",
    "le_mans_purple",
    "monaco_signal",
    "sakura_sprint",
    "lime_attack",
    "carbon_red",
    "fuji_sunset",
    "custom",
]


PREBUILT_PIXEL_THEMES: dict[str, dict[str, str]] = {
    "simdt_blue": {
        "gear": "31d7ff",
        "rev_low": "26d8ff",
        "rev_mid": "ff96f0",
        "rev_high": "ff3d86",
        "shift": "ff4aa8",
        "fuel_safe": "26d8ff",
        "fuel_warn": "ff96f0",
        "fuel_danger": "ff3d86",
        "fuel_critical": "ff2d2d",
    },
    "warm_amber": {
        "gear": "ff8a24",
        "rev_low": "ff9f2e",
        "rev_mid": "ff5f1a",
        "rev_high": "c51616",
        "shift": "ff2400",
        "fuel_safe": "ffb347",
        "fuel_warn": "ff8a24",
        "fuel_danger": "ff4b1f",
        "fuel_critical": "c51616",
    },
    "race_gyr": {
        "gear": "f5f8ff",
        "rev_low": "00d36f",
        "rev_mid": "ffd21f",
        "rev_high": "ff2d2d",
        "shift": "ff2d2d",
        "fuel_safe": "00d36f",
        "fuel_warn": "ffd21f",
        "fuel_danger": "ff7a1f",
        "fuel_critical": "ff2d2d",
    },
    "arcade_neon": {
        "gear": "e6fff9",
        "rev_low": "00f0ff",
        "rev_mid": "ffea00",
        "rev_high": "ff3df2",
        "shift": "ffffff",
        "fuel_safe": "00f0ff",
        "fuel_warn": "ffea00",
        "fuel_danger": "ff3df2",
        "fuel_critical": "ff2d55",
    },
    "pit_lane_white": {
        "gear": "f8fbff",
        "rev_low": "64d2ff",
        "rev_mid": "ffd166",
        "rev_high": "ef476f",
        "shift": "ffffff",
        "fuel_safe": "57cc99",
        "fuel_warn": "ffd166",
        "fuel_danger": "f77f00",
        "fuel_critical": "ef233c",
    },
    "night_vision": {
        "gear": "b7ff3c",
        "rev_low": "56e000",
        "rev_mid": "ff9f1c",
        "rev_high": "ff2d2d",
        "shift": "ff2d2d",
        "fuel_safe": "56e000",
        "fuel_warn": "ffe66d",
        "fuel_danger": "ff9f1c",
        "fuel_critical": "ff4d4d",
    },
    "gulf_classic": {
        "gear": "8bd3ff",
        "suggested_gear": "ff6b35",
        "rev_low": "7bd389",
        "rev_mid": "ffb703",
        "rev_high": "ff6b35",
        "shift": "ff6b35",
        "fuel_safe": "7bd389",
        "fuel_warn": "ffb703",
        "fuel_danger": "ff6b35",
        "fuel_critical": "e63946",
    },
    "ice_rally": {
        "gear": "d8fbff",
        "rev_low": "73d2de",
        "rev_mid": "b8f2e6",
        "rev_high": "ff7f50",
        "shift": "ffffff",
        "fuel_safe": "73d2de",
        "fuel_warn": "f4d35e",
        "fuel_danger": "ff7f50",
        "fuel_critical": "ee4266",
    },
    "le_mans_purple": {
        "gear": "d7c4ff",
        "rev_low": "00e5a8",
        "rev_mid": "ffd23f",
        "rev_high": "ff4d8d",
        "shift": "f9f7ff",
        "fuel_safe": "00e5a8",
        "fuel_warn": "ffd23f",
        "fuel_danger": "ff8c42",
        "fuel_critical": "ff4d8d",
    },
    "monaco_signal": {
        "gear": "f7f5f0",
        "rev_low": "00a6a6",
        "rev_mid": "ffca3a",
        "rev_high": "e63946",
        "shift": "ffffff",
        "fuel_safe": "00a6a6",
        "fuel_warn": "ffca3a",
        "fuel_danger": "f77f00",
        "fuel_critical": "e63946",
    },
    "sakura_sprint": {
        "gear": "ffd6e7",
        "rev_low": "7bdff2",
        "rev_mid": "f6d365",
        "rev_high": "ff5c8a",
        "shift": "ffffff",
        "fuel_safe": "7bdff2",
        "fuel_warn": "f6d365",
        "fuel_danger": "ff8fab",
        "fuel_critical": "ff2f6d",
    },
    "lime_attack": {
        "gear": "d8ff3e",
        "rev_low": "6eeb83",
        "rev_mid": "ffee32",
        "rev_high": "ff5714",
        "shift": "ffffff",
        "fuel_safe": "6eeb83",
        "fuel_warn": "ffee32",
        "fuel_danger": "ff9f1c",
        "fuel_critical": "ff5714",
    },
    "carbon_red": {
        "gear": "ff3b30",
        "rev_low": "8f0f1f",
        "rev_mid": "d72638",
        "rev_high": "ff1f1f",
        "shift": "ff0000",
        "fuel_safe": "b11226",
        "fuel_warn": "ff4d2e",
        "fuel_danger": "ff1f1f",
        "fuel_critical": "b00020",
    },
    "fuji_sunset": {
        "gear": "ff7a59",
        "rev_low": "ff6b35",
        "rev_mid": "ff3d5a",
        "rev_high": "d0005b",
        "shift": "ff1744",
        "fuel_safe": "ff6b35",
        "fuel_warn": "ff3d5a",
        "fuel_danger": "fb5607",
        "fuel_critical": "d0005b",
    },
}

PIXEL_COLOR_THEMES = cast(
    tuple[PixelColorTheme, ...],
    (*PREBUILT_PIXEL_THEMES.keys(), "custom"),
)
